name: "\U0001F4DD Suggest a change"
description: "Share your idea for how to make the website better"
title: "Suggestion: (fill in)"
labels:
  - enhancement
body:
- type: markdown
  attributes:
    value: By opening an issue, you agree to abide by the [Open JS Foundation Code of Conduct](https://eslint.org/conduct).
- type: textarea
  attributes:
    label: What problem do you want to solve?
    description: |
      Please explain your use case in as much detail as possible.
    placeholder: |
      The website currently...
  validations:
    required: true
- type: textarea
  attributes:
    label: What do you think is the correct solution?
    description: |
      Please explain how you'd like to change the website to address the problem.
    placeholder: |
      I'd like to...
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Participation
    options:
      - label: I am willing to submit a pull request for this change.
        required: false
- type: textarea
  attributes:
    label: Additional comments
    description: Is there anything else that's important for the team to know?
